SALT: "\x12\xAC\x13GH\xE7\xFA\x8B\x7F\xE5w\x14\x14\xBF\xF7J, O\x88n5\xB2\xF3\x866G\xF9\x93E\xB1\x8D"
CRYPT_KEY: "2\xBBJ\xDB2\xA8\xDBY\x1An\xBC0*\f\xC3s\x01\xCBb\x81\xC7\x18\x82LA\x96\xD1\x1A\xBC>\x17\x8A"